In [41]:
#library
import numpy as np

# Week 2

# Valid
a=np.random.randn(x,y)
b=np.random.randn(m,n)


Either (x==m) or (y==n) or (x==m and y==n)

In [17]:
a=np.random.randn(4,3)
print(a)
b=np.random.randn(1,3)
print(b)

[[-0.69650687  0.18436641  0.73298928]
 [ 0.17757935 -0.72994348  1.16332026]
 [ 0.00457253 -0.24373292  0.95254357]
 [ 1.23530726 -0.51251347  0.23758984]]
[[ 0.10900069  0.90332741 -0.05965927]]


In [19]:
a=np.random.randn(4,3)
print(a)
b=np.random.randn(4,1)
print(b)

[[-0.9460686   0.19922777  0.60187995]
 [ 0.58826342  2.6305495   0.33693522]
 [ 1.4404953   0.82164868 -0.71494922]
 [-2.46082069 -1.63853435  1.67161391]]
[[ 1.46518627]
 [ 0.37719531]
 [-0.97253299]
 [-0.20787268]]


# Invalid

In [21]:
#Invalid
a=np.random.randn(4,3)
print(a)
b=np.random.randn(1,2)
print(b)
a*b

[[-1.04171822 -1.79283083  0.04393663]
 [ 0.06330726 -0.33175611  0.59291094]
 [-0.14309163  0.56881609  0.11275846]
 [ 2.72556411 -0.1496551   0.22684698]]
[[-0.16961219  0.09031098]]


ValueError: operands could not be broadcast together with shapes (4,3) (1,2) 

In [29]:
# a.shape = (3,4)
# b.shape = (4,1)


a=np.random.rand(3,4)
b=np.random.rand(4)
c=np.ones((3,4))

for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]
print(c)

[[1.07433459 1.24949239 0.59078818 0.96927135]
 [1.51534389 1.01042753 0.74554381 1.42466218]
 [1.01511171 1.1000548  0.39036869 1.71861116]]


Question:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [40]:
#Matrix multiplication operation occur

a = np.random.randn(3, 3)
print(a);print()
b = np.random.randn(3, 1)
print(b);print()
c = a*b
print(c)

[[-0.61340965 -1.05485647  0.33089931]
 [ 0.40264363  0.49728603 -0.60185132]
 [ 0.506952   -0.70628948  0.33711685]]

[[-0.27591101]
 [-3.4230555 ]
 [ 1.53337162]]

[[ 0.16924648  0.29104652 -0.09129876]
 [-1.37827149 -1.70223766  2.06017048]
 [ 0.77734582 -1.08300425  0.5169254 ]]


# Week 3

In [63]:
A =np.random.randint(10,size=(3,1))
print(A)
B = np.sum(A, axis = 1, keepdims = True)
B.shape

[[7]
 [2]
 [2]]


(3, 1)

In [64]:
B

array([[7],
       [2],
       [2]])